//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SimpleFormAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int uid { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage="User Name Required")]
        public string UseName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password Required")]
        public string Password { get; set; }

        public string LogginErrorMessage { get; set; }
    }
}
